# Apply label "🚀 Dev" if - head-branch branch matches dev-frontend
🚀 Dev:
  - base-branch: "dev-frontend"

🧪 QA:
  - base-branch: "qa-frontend"

✅ UAT:
  - base-branch: "uat-frontend"

# 🧪 QA to ✅ UAT:
#   - base-branch: "uat-frontend"
#     head-branch: "qa-frontend"

# 🚀 Dev to 🧪 QA:
#   - base-branch: "qa-frontend"
#     head-branch: "dev-frontend"
